# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'log_in.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import os
import random
from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Log_in(object):

    def setupUi(self, Log_in):
        Log_in.setObjectName("Log_in")
        Log_in.setFixedSize(1024, 764)
        Log_in.setWindowFlags(QtCore.Qt.Window | QtCore.Qt.WindowMinimizeButtonHint | QtCore.Qt.WindowCloseButtonHint)
        Log_in.setStyleSheet("# Apply styles to the textbox\n"
                            "textbox.setStyleSheet(\'\'\'\n"
                            "    QLineEdit {\n"
                            "        background-color: #F2F2F2;\n"
                            "        border: 1px solid #CCCCCC;\n"
                            "        border-radius: 5px;\n"
                            "        color: #333333;\n"
                            "        padding: 5px;\n"
                            "        margin: 5px;\n"
                            "    }\n"
                            "\n"
                            "    QLineEdit:focus {\n"
                            "        border-color: #4C9AFF;\n"
                            "        box-shadow: 0 0 5px rgba(76, 154, 255, 0.5);\n"
                            "    }\n"
                            "\n"
                            "    QLineEdit:hover {\n"
                            "        background-color: #E5E5E5;\n"
                            "    }\n"
                            "\'\'\')\n"
                            "")
        self.centralwidget = QtWidgets.QWidget(Log_in)
        self.centralwidget.setObjectName("centralwidget")
        self.Image = QtWidgets.QLabel(self.centralwidget)
        self.Image.setGeometry(QtCore.QRect(-24, 0, 650, 764))
        self.Image.setText("")

        # Specify the folder path where the images are stored
        image_folder = "../Assets/Log in pages"

        # Get the list of image files in the folder
        image_files = [f for f in os.listdir(image_folder) if os.path.isfile(os.path.join(image_folder, f))]

        # Select a random image from the list
        random_image = random.choice(image_files)

        # Set the pixmap of the QLabel to the random image
        self.Image.setPixmap(QtGui.QPixmap(os.path.join(image_folder, random_image)))
        
        self.Image.setScaledContents(True)
        self.Image.setObjectName("Image")
        self.Righ_side = QtWidgets.QLabel(self.centralwidget)
        self.Righ_side.setGeometry(QtCore.QRect(626, 0, 398, 768))
        self.Righ_side.setText("")
        self.Righ_side.setPixmap(QtGui.QPixmap("../Assets/Log in pages/white.png"))
        self.Righ_side.setScaledContents(True)
        self.Righ_side.setObjectName("Righ_side")
        self.Password_Testbox = QtWidgets.QLineEdit(self.centralwidget)
        self.Password_Testbox.setGeometry(QtCore.QRect(696, 390, 258, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Password_Testbox.setFont(font)
        self.Password_Testbox.setAutoFillBackground(False)
        self.Password_Testbox.setStyleSheet("border: none;\n"
                                            "        border-bottom: 1px solid #CCCCCC;\n"
                                            "        background-color: transparent;\n"
                                            "        color: #333333;\n"
                                            "        padding: 5px;")
        self.Password_Testbox.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password_Testbox.setPlaceholderText("Password")
        self.Password_Testbox.setObjectName("Password_Testbox")
        self.Welcome_Header = QtWidgets.QLabel(self.centralwidget)
        self.Welcome_Header.setGeometry(QtCore.QRect(660, 90, 321, 261))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.Welcome_Header.setFont(font)
        self.Welcome_Header.setAcceptDrops(False)
        self.Welcome_Header.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Welcome_Header.setWordWrap(True)
        self.Welcome_Header.setObjectName("Welcome_Header")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(696, 460, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        Log_in.setCentralWidget(self.centralwidget)

        self.retranslateUi(Log_in)
        QtCore.QMetaObject.connectSlotsByName(Log_in)

        self.Password_Testbox.textChanged.connect(self.handlePasswordTextChanged)
        self.checkBox.stateChanged.connect(self.handleShowPassword)

    def retranslateUi(self, Log_in):
        _translate = QtCore.QCoreApplication.translate
        Log_in.setWindowTitle(_translate("Log_in", "MainWindow"))
        self.Welcome_Header.setText(_translate("Log_in", "Welcome Back, {name} Prajajajajapti Kumar")) # TODO: Handle Name here.
        self.checkBox.setText(_translate("Log_in", "Show Password"))

    def handlePasswordTextChanged(self, text):
        if text:
            self.Password_Testbox.setPlaceholderText("")
        else:
            self.Password_Testbox.setPlaceholderText("Password")

    def handleShowPassword(self, state):
        if state == QtCore.Qt.Checked:
            self.Password_Testbox.setEchoMode(QtWidgets.QLineEdit.Normal)
        else:
            self.Password_Testbox.setEchoMode(QtWidgets.QLineEdit.Password)

 



class LogInWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        self.ui = Ui_Log_in()
        self.ui.setupUi(self)

        # Customize the window title
        self.setWindowTitle("Budget App") # TODO: Replace to App name

        # Set the window icon
        self.setWindowIcon(QtGui.QIcon("../Assets/icon.png")) # TODO: Replace to app's icon

        # Show the main window
        self.show()

if __name__ == "__main__":
    # Create the application instance
    app = QApplication(sys.argv)

    # Create and show the login window
    login_window = LogInWindow()

    # Execute the application event loop
    sys.exit(app.exec())


    # TODO: Enter to excute next page. And Password checking..